spring.application.name=mixer
spring.config.import=optional:classpath:application-local.properties
spring.web.error.include-stacktrace=never

# JobRunr
jobrunr.job-scheduler.enabled=true
jobrunr.background-job-server.enabled=true
jobrunr.dashboard.enabled=true
jobrunr.dashboard.port=8000

# Exposed ORM
spring.exposed.generate-ddl=true

# Spring Session
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

# Mixer - schedules
mixer.refresh.aggregations.interval=300000
mixer.refresh.aggregations.initial=10000
mixer.refresh.fx.interval=300000
mixer.refresh.fx.initial=10000

# Mixer - supported currencies
mixer.fx.currencies=EUR,GBP,AUD,NZD,USD,HKD