spring.application.name=mixer
spring.web.error.include-stacktrace=never
jobrunr.job-scheduler.enabled=true
jobrunr.background-job-server.enabled=true
jobrunr.dashboard.enabled=true
jobrunr.dashboard.port=8000
spring.exposed.generate-ddl=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.session.jdbc.initialize-schema=always